### ISSUE TITLE
Can anyone explain?

### ISSUE THREAD

**Issue by BRxPyro** [ichttt/FirstAid#228] opened 2024-02-26 11:50 UTC
a friend of mine tried to join my game,, were both running the exact same mod pack and he received this error. None of us really understand what this means and any help would be great thnaks 

The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "java.util.Map.getOrDefault(Object, Object)" because "ichttt.mods.firstaid.common.registries.FirstAidRegistryLookups.DEBUFF_BUILDERS" is null

**Comment by Nicknamee12** [comment] 2024-02-26 21:47
Have the same issue, a way to get around the issue is to /kill the player after they join but before their game has time to crash

**Comment by ichttt** [comment] 2024-02-28 08:32
Can you send me the complete log?

**Comment by ichttt** [comment] 2024-07-06 11:14
Same as #236 btw. I still have not received a single complete bug report of this with steps how to reproduce, environment or even a complete log file...

**Comment by Nicknamee12** [comment] 2024-07-07 20:35
@ichttt 
Cannot figure out for the life of me what actually causes the crash (added and removed different mods for a few hrs and nothing was consistent) and the crash only seems to occur when joining a dedicated server. Here are a few crash logs as well as a curse forge profile that includes all the mods that i was using.

(If u also need the dedicated server files i can send it but the file was too large for github to have as a attachment)

(curse forge profile also includes more crash logs with other mods)
[curse forge app profile.zip](https://github.com/user-attachments/files/16120678/curse.forge.app.profile.zip)
[crash-2024-07-07_15.42.01-client.txt](https://github.com/user-attachments/files/16120681/crash-2024-07-07_15.42.01-client.txt)
[crash-2024-07-07_15.50.46-client.txt](https://github.com/user-attachments/files/16120682/crash-2024-07-07_15.50.46-client.txt)
[crash-2024-07-07_16.02.03-client.txt](https://github.com/user-attachments/files/16120683/crash-2024-07-07_16.02.03-client.txt)
[crash-2024-07-07_16.16.08-client.txt](https://github.com/user-attachments/files/16120684/crash-2024-07-07_16.16.08-client.txt)
[crash-2024-07-07_16.19.15-client.txt](https://github.com/user-attachments/files/16120685/crash-2024-07-07_16.19.15-client.txt)
[crash-2024-07-07_16.29.55-client.txt](https://github.com/user-attachments/files/16120686/crash-2024-07-07_16.29.55-client.txt)

**Comment by ichttt** [comment] 2024-07-14 12:44
Thanks a lot! I was able to reproduce this, and have a fix pending for the next version (https://github.com/ichttt/FirstAid/commit/aeaaf59c54dc99292c38f18a6735beeca1f844e4)

**Comment by ichttt** [comment] 2024-07-14 18:41
Should be fixed in 1.20.1-1.1

**Closed as completed by ichttt** 2024-07-14 18:41 UTC
Labels: bug
