### ISSUE TITLE
1.12.2 Dying issue.

### ISSUE THREAD

**Issue by RupticMC** [ichttt/FirstAid#67] opened 2019-12-05 07:44 UTC
I am currently using a server software that allows me to use Spigot+Forge for 1.12.2 (attempted using both CatServer and Mohist). I know this is a server software issue but it seems like they are currently having troubles fixing it and others say they cannot fix it. But whenever a player "dies", it pops up with a dead screen to click "Respawn". When they click "Respawn", they never respawn and their health and body is glitched to where they actually can no longer get hurt. I do not get any errors but was seeing if it was possible to get a "hotfix" of some sort. I have this running on the latest version of RLCraft. 

Config: https://paste.helpch.at/opakoyewoq.coffeescript

**Comment by ichttt** [comment] 2020-01-29 00:49
Please retest on 1.6.13

**Comment by RupticMC** [comment] 2020-01-29 01:33
Seems to be broken as well.

**Comment by RupticMC** [comment] 2020-01-29 01:49
Yeah, seems to be broken like in the older version.

**Comment by ichttt** [comment] 2020-01-29 10:08
Can you please send me the broken world?

**Comment by RupticMC** [comment] 2020-01-29 12:58
All you have to do is download RLCraft and Catserver (server software) them run it.

**Comment by ichttt** [comment] 2020-01-29 14:26
The problem seems like this thrid-party server does not use the datamanger for player.getHealth(), like the vanilla and forge implementation does. This breaks FirstAid, as it sets the datamager value directly. Report this to the authors of the server.

**Comment by ichttt** [comment] 2020-03-31 14:51
Closing, as I can't reproduce this with just forge and first aid and this is missing further input

**Closed by ichttt** 2020-03-31 14:51 UTC
Labels: bug
