### ISSUE TITLE
Blindness diffuse applied even when fully disabled

### ISSUE THREAD

**Issue by mojoyup1528** [ichttt/FirstAid#64] opened 2019-11-21 16:39 UTC
Windows 10 Home 64
Forge latest 1.12.2
4G mem allocation

Hello! I wanted to post an issue about diffuse effects. When I disable the blindness, either by config file and/or ingame, the effect still exists. Single player survival mode in focus. 

Thank you :)

**Comment by ichttt** [comment] 2020-01-28 22:33
Cannot reproduce, can you please send me your config file? I simply set B:blindness to false in the config file. Make sure to restart your minecraft after chaning the setting.

**Comment by ichttt** [comment] 2020-02-29 13:38
Closing due to missing feedback

**Closed by ichttt** 2020-02-29 13:38 UTC
