### ISSUE TITLE
crashing client when joining a server

### ISSUE THREAD

**Issue by DoofusGamer** [ichttt/FirstAid#232] opened 2024-03-17 15:05 UTC
There's a small chance that when joining a server the client crashes 
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-03-17 09:56:33
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "java.util.Map.getOrDefault(Object, Object)" because "ichttt.mods.firstaid.common.registries.FirstAidRegistryLookups.DEBUFF_BUILDERS" is null

This is the first line of the crash report and looking through configs and the .jar file of the mod itself I can't find anything for "DEBUFF_BUILDERS"

**Comment by Jaedon-UVU** [comment] 2024-03-20 02:02
I've also had this issue, it seems to happen when I get some amount of mods. It's hard to determine if its conflicting with a specific thing or several. Because it will work with mods when its just those two mods or a few other mods, but after a point it will provide that error.

**Comment by ShadowFantasy** [comment] 2024-03-20 02:18
What other mods do you have? I also have this issue and have a bunch of mods, and I am trying to narrow down the problem because it seems there is either multiple mods that conflict with it or there are multiple mods that create a problem if included together.

Also what version of Forge are you using?

**Comment by SGSxingchen** [comment] 2024-03-31 11:19
[crash-2024-03-31_19.09.23-client.txt](https://github.com/ichttt/FirstAid/files/14815170/crash-2024-03-31_19.09.23-client.txt)
Same question

**Comment by ichttt** [comment] 2024-07-06 11:11
Same as #236, but I just can not reproduce this. What other mods are involved? Does in only happen when connecting to a server or on singleplayer as well?

**Comment by ichttt** [comment] 2024-07-14 18:41
Should be fixed in 1.20.1-1.1

**Closed as completed by ichttt** 2024-07-14 18:41 UTC
Labels: bug
